### ISSUE TITLE
Auth server Not remembering players login password and when logging in after registering it will redirect you even without loggining in.

### ISSUE THREAD

**Issue by megatron0001** [Elytrium/ElytraProxy#3]
This was the error message I got

---------------------------------------------------------------------------------------------------------------------------------------

[17:45:46 ERROR]: java.sql.SQLFeatureNotSupportedException
[17:45:46 ERROR]:       at org.sqlite.jdbc4.JDBC4ResultSet.getObject(JDBC4ResultSet.java:343)
[17:45:46 ERROR]:       at net.elytrium.elytraproxy.database.MySqlDatabase.serializeFromSet(MySqlDatabase.java:210)
[17:45:46 ERROR]:       at net.elytrium.elytraproxy.database.MySqlDatabase.queryResult(MySqlDatabase.java:146)
[17:45:46 ERROR]:       at net.elytrium.elytraproxy.database.MySqlDatabase.getItem(MySqlDatabase.java:125)
[17:45:46 ERROR]:       at net.elytrium.elytraproxy.auth.handler.AuthSessionHandler.fetchInfo(AuthSessionHandler.java:142)
[17:45:46 ERROR]:       at net.elytrium.elytraproxy.auth.handler.AuthSessionHandler.fetchInfo(AuthSessionHandler.java:149)
[17:45:46 ERROR]:       at net.elytrium.elytraproxy.auth.handler.AuthSessionHandler.<init>(AuthSessionHandler.java:68)
[17:45:46 ERROR]:       at net.elytrium.elytraproxy.ElytraProxy.sendToAuthServer(ElytraProxy.java:265)
[17:45:46 ERROR]:       at net.elytrium.elytraproxy.ElytraProxy.lambda$auth$0(ElytraProxy.java:246)
[17:45:46 ERROR]:       at org.asynchttpclient.netty.NettyResponseFuture.lambda$addListener$0(NettyResponseFuture.java:294)
[17:45:46 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
[17:45:46 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
[17:45:46 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
[17:45:46 ERROR]:       at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[17:45:46 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[17:45:46 ERROR]:       at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[17:45:46 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[17:45:46 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[17:45:46 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[17:45:46 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:831)
[17:45:46 ERROR]: java.sql.SQLFeatureNotSupportedException
[17:45:46 ERROR]:       at org.sqlite.jdbc4.JDBC4ResultSet.getObject(JDBC4ResultSet.java:343)
[17:45:46 ERROR]:       at net.elytrium.elytraproxy.database.MySqlDatabase.serializeFromSet(MySqlDatabase.java:210)
[17:45:46 ERROR]:       at net.elytrium.elytraproxy.database.MySqlDatabase.queryResultList(MySqlDatabase.java:171)
[17:45:46 ERROR]:       at net.elytrium.elytraproxy.database.MySqlDatabase.getItems(MySqlDatabase.java:136)
[17:45:46 ERROR]:       at net.elytrium.elytraproxy.auth.handler.AuthSessionHandler.checkIp(AuthSessionHandler.java:160)
[17:45:46 ERROR]:       at net.elytrium.elytraproxy.auth.handler.AuthSessionHandler.onSpawn(AuthSessionHandler.java:133)
[17:45:46 ERROR]:       at net.elytrium.elytraproxy.virtual.server.VirtualServer.spawnPlayer(VirtualServer.java:51)
[17:45:46 ERROR]:       at net.elytrium.elytraproxy.ElytraProxy.sendToAuthServer(ElytraProxy.java:268)
[17:45:46 ERROR]:       at net.elytrium.elytraproxy.ElytraProxy.lambda$auth$0(ElytraProxy.java:246)
[17:45:46 ERROR]:       at org.asynchttpclient.netty.NettyResponseFuture.lambda$addListener$0(NettyResponseFuture.java:294)
[17:45:46 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
[17:45:46 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
[17:45:46 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
[17:45:46 ERROR]:       at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[17:45:46 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[17:45:46 ERROR]:       at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[17:45:46 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[17:45:46 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[17:45:46 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[17:45:46 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:831)
[17:45:46 ERROR] [ElytraProxy]: Error
java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because "alreadyRegistered" is null
        at net.elytrium.elytraproxy.auth.handler.AuthSessionHandler.checkIp(AuthSessionHandler.java:166) ~[elytraproxy-proxy-3.0.1-SNAPSHOT-all.jar:3.0.1-SNAPSHOT (git-ec86936b-bunknown)]
        at net.elytrium.elytraproxy.auth.handler.AuthSessionHandler.onSpawn(AuthSessionHandler.java:133) ~[elytraproxy-proxy-3.0.1-SNAPSHOT-all.jar:3.0.1-SNAPSHOT (git-ec86936b-bunknown)]
        at net.elytrium.elytraproxy.virtual.server.VirtualServer.spawnPlayer(VirtualServer.java:51) ~[elytraproxy-proxy-3.0.1-SNAPSHOT-all.jar:3.0.1-SNAPSHOT (git-ec86936b-bunknown)]
        at net.elytrium.elytraproxy.ElytraProxy.sendToAuthServer(ElytraProxy.java:268) ~[elytraproxy-proxy-3.0.1-SNAPSHOT-all.jar:3.0.1-SNAPSHOT (git-ec86936b-bunknown)]
        at net.elytrium.elytraproxy.ElytraProxy.lambda$auth$0(ElytraProxy.java:246) ~[elytraproxy-proxy-3.0.1-SNAPSHOT-all.jar:3.0.1-SNAPSHOT (git-ec86936b-bunknown)]
        at org.asynchttpclient.netty.NettyResponseFuture.lambda$addListener$0(NettyResponseFuture.java:294) ~[elytraproxy-proxy-3.0.1-SNAPSHOT-all.jar:3.0.1-SNAPSHOT (git-ec86936b-bunknown)]
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[elytraproxy-proxy-3.0.1-SNAPSHOT-all.jar:3.0.1-SNAPSHOT (git-ec86936b-bunknown)]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[elytraproxy-proxy-3.0.1-SNAPSHOT-all.jar:3.0.1-SNAPSHOT (git-ec86936b-bunknown)]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[elytraproxy-proxy-3.0.1-SNAPSHOT-all.jar:3.0.1-SNAPSHOT (git-ec86936b-bunknown)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[elytraproxy-proxy-3.0.1-SNAPSHOT-all.jar:3.0.1-SNAPSHOT (git-ec86936b-bunknown)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[elytraproxy-proxy-3.0.1-SNAPSHOT-all.jar:3.0.1-SNAPSHOT (git-ec86936b-bunknown)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[elytraproxy-proxy-3.0.1-SNAPSHOT-all.jar:3.0.1-SNAPSHOT (git-ec86936b-bunknown)]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by megatron0001** [comment]
# Why is no one helping me 
bruh

**Comment by hevav** [comment]
That means that your SQLite DB file is broken. Delete SQLite file (ElytraProxy will make a new one) or use MySQL in config.yml

**Comment by megatron0001** [comment]
> That means that your SQLite DB file is broken. Delete SQLite file (ElytraProxy will make a new one) or use MySQL in config.yml

I did that but It's still doing the same thing and I don't now how to use MySQL

**Comment by megatron0001** [comment]
> That means that your SQLite DB file is broken. Delete SQLite file (ElytraProxy will make a new one) or use MySQL in config.yml

Hello?

**Comment by megatron0001** [comment]
> That means that your SQLite DB file is broken. Delete SQLite file (ElytraProxy will make a new one) or use MySQL in config.yml

Hello that not working.
